//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayGCon.Resource.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayGCon.Resource.Resx.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;log&quot; : {
        ///		&quot;access&quot; : &quot;文件地址&quot;,
        ///		&quot;error&quot; : &quot;文件地址&quot;,
        ///		&quot;loglevel&quot; : &quot;warning&quot;
        ///	},
        ///	&quot;inbound&quot; : {
        ///		&quot;port&quot; : 1080,
        ///		&quot;listen&quot; : &quot;127.0.0.1&quot;,
        ///		&quot;protocol&quot; : &quot;socks&quot;,
        ///		&quot;settings&quot; : {
        ///			&quot;auth&quot; : &quot;noauth&quot;,
        ///			&quot;udp&quot; : false,
        ///			&quot;ip&quot; : &quot;127.0.0.1&quot;
        ///		},
        ///		&quot;streamSettings&quot; : {},
        ///		&quot;tag&quot; : &quot;标识1&quot;,
        ///		&quot;domainOverride&quot; : [&quot;http&quot;, &quot;tls&quot;]
        ///	},
        ///	&quot;outbound&quot; : {
        ///		&quot;sendThrough&quot; : &quot;0.0.0.0&quot;,
        ///		&quot;protocol&quot; : &quot;freedom&quot;,
        ///		&quot;settings&quot; : {},
        ///		&quot;tag&quot; : &quot;direct&quot;,
        ///		&quot;streamSettings&quot; : {},
        ///		&quot;proxySettings&quot; : {
        ///			&quot;tag&quot; : &quot;another-out [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_def {
            get {
                return ResourceManager.GetString("config_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;log&quot;: {
        ///    &quot;loglevel&quot;: &quot;warning&quot;
        ///  },
        ///  &quot;inbound&quot;: {
        ///    &quot;port&quot;: 1080,
        ///    &quot;listen&quot;: &quot;127.0.0.1&quot;,
        ///    &quot;protocol&quot;: &quot;socks&quot;,
        ///    &quot;settings&quot;: {
        ///      &quot;auth&quot;: &quot;noauth&quot;,
        ///      &quot;udp&quot;: false,
        ///      &quot;ip&quot;: &quot;127.0.0.1&quot;
        ///    }
        ///  },
        ///  &quot;outbound&quot;: {
        ///    &quot;protocol&quot;: &quot;freedom&quot;,
        ///    &quot;settings&quot;: {},
        ///    &quot;tag&quot;: &quot;direct&quot;
        ///  },
        ///  &quot;policy&quot;: {
        ///    &quot;levels&quot;: {
        ///      &quot;0&quot;: {&quot;uplinkOnly&quot;: 0}
        ///    }
        ///  }
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string config_min {
            get {
                return ResourceManager.GetString("config_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;vmessClient&quot; : {
        ///		&quot;vnext&quot; : [{
        ///				&quot;address&quot; : &quot;127.0.0.1&quot;,
        ///				&quot;port&quot; : 37192,
        ///				&quot;users&quot; : [{
        ///						&quot;id&quot; : &quot;27848739-7e62-4138-9fd3-098a63964b6b&quot;,
        ///						&quot;alterId&quot; : 10,
        ///						&quot;security&quot; : &quot;auto&quot;,
        ///						&quot;level&quot; : 0
        ///					}
        ///				]
        ///			}
        ///		]
        ///	},
        ///	&quot;ssrClient&quot; : {
        ///		&quot;servers&quot; : [{
        ///				&quot;email&quot; : &quot;love@v2ray.com&quot;,
        ///				&quot;address&quot; : &quot;127.0.0.1&quot;,
        ///				&quot;port&quot; : 1234,
        ///				&quot;method&quot; : &quot;aes-256-gcm&quot;,
        ///				&quot;password&quot; : &quot;pass&quot;,
        ///				&quot;ota&quot; : false,
        ///				&quot;level&quot; : 0
        ///			}
        ///		]
        ///	},
        ///	&quot;kcp&quot; : {
        ///		&quot;network&quot; : &quot;kcp&quot;,
        ///		&quot;security&quot; : [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_tpl {
            get {
                return ResourceManager.GetString("config_tpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;log&quot; : {
        ///		&quot;loglevel&quot; : &quot;warning&quot;
        ///	},
        ///	&quot;inbound&quot; : {
        ///		&quot;port&quot; : 1080,
        ///		&quot;listen&quot; : &quot;127.0.0.1&quot;,
        ///		&quot;protocol&quot; : &quot;socks&quot;,
        ///		&quot;settings&quot; : {
        ///			&quot;auth&quot; : &quot;noauth&quot;,
        ///			&quot;udp&quot; : false,
        ///			&quot;ip&quot; : &quot;127.0.0.1&quot;
        ///		}
        ///	},
        ///	&quot;outbound&quot; : {
        ///		&quot;protocol&quot; : &quot;freedom&quot;,
        ///		&quot;settings&quot; : null,
        ///		&quot;tag&quot; : &quot;direct&quot;,
        ///		&quot;mux&quot; : null,
        ///		&quot;streamSettings&quot; : null
        ///	}
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string config_vmess_tpl {
            get {
                return ResourceManager.GetString("config_vmess_tpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 config.json 的本地化字符串。
        /// </summary>
        internal static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/v2ray/v2ray-core/releases/download/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string DownloadLinkTpl {
            get {
                return ResourceManager.GetString("DownloadLinkTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmess://ew0KICAicHMiOiAiZHVtbXkxIiwNCiAgImFkZCI6ICIxLjIuMy40IiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImI4NzNkNWY0LTMyNjEtNGYxOS04MGE3LWYwZTY3YzkwYzA4MiIsDQogICJhaWQiOiAiMTAwIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIvcmF5IiwNCiAgInRscyI6ICJ0bHMiDQp9 的本地化字符串。
        /// </summary>
        internal static string DummyServ1 {
            get {
                return ResourceManager.GetString("DummyServ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmess://ew0KICAicHMiOiAiZHVtbXkyIiwNCiAgImFkZCI6ICIyLjMuNC41IiwNCiAgInBvcnQiOiAiMTIzNCIsDQogICJpZCI6ICI1NjIxODM4ZS1hYmM1LTRiNmQtOWQzMS00MmUwOGE3ZWMzMmYiLA0KICAiYWlkIjogIjY0IiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInRscyI6ICIiDQp9 的本地化字符串。
        /// </summary>
        internal static string DummyServ2 {
            get {
                return ResourceManager.GetString("DummyServ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray.exe 的本地化字符串。
        /// </summary>
        internal static string Executable {
            get {
                return ResourceManager.GetString("Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2ray-core has exited! 的本地化字符串。
        /// </summary>
        internal static string Exited {
            get {
                return ResourceManager.GetString("Exited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 png files (*.png)|*.png|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string ExtPng {
            get {
                return ResourceManager.GetString("ExtPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4}) 的本地化字符串。
        /// </summary>
        internal static string PatternBase64 {
            get {
                return ResourceManager.GetString("PatternBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray-windows-32.zip 的本地化字符串。
        /// </summary>
        internal static string PkgWin32 {
            get {
                return ResourceManager.GetString("PkgWin32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray-windows-64.zip 的本地化字符串。
        /// </summary>
        internal static string PkgWin64 {
            get {
                return ResourceManager.GetString("PkgWin64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&apos;servers&apos;:[&apos;8.8.8.8&apos;,&apos;8.8.4.4&apos;,&apos;localhost&apos;]} 的本地化字符串。
        /// </summary>
        internal static string TplDNS {
            get {
                return ResourceManager.GetString("TplDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&apos;network&apos;:&apos;kcp&apos;,&apos;security&apos;:&apos;&apos;,&apos;tcpSettings&apos;:null,&apos;kcpSettings&apos;:{&apos;mtu&apos;:1350,&apos;tti&apos;:50,&apos;uplinkCapacity&apos;:12,&apos;downlinkCapacity&apos;:100,&apos;congestion&apos;:false,&apos;readBufferSize&apos;:2,&apos;writeBufferSize&apos;:2,&apos;header&apos;:{&apos;type&apos;:&apos;&apos;,&apos;request&apos;:null,&apos;response&apos;:null}},&apos;wsSettings&apos;:null} 的本地化字符串。
        /// </summary>
        internal static string TplKCP {
            get {
                return ResourceManager.GetString("TplKCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{&apos;protocol&apos;:&apos;freedom&apos;,&apos;settings&apos;:{&apos;response&apos;:null},&apos;tag&apos;:&apos;direct&apos;},{&apos;protocol&apos;:&apos;blackhole&apos;,&apos;settings&apos;:{&apos;response&apos;:{&apos;type&apos;:&apos;http&apos;}},&apos;tag&apos;:&apos;blockout&apos;}] 的本地化字符串。
        /// </summary>
        internal static string TplOutDetour {
            get {
                return ResourceManager.GetString("TplOutDetour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&apos;strategy&apos;:&apos;rules&apos;,&apos;settings&apos;:{&apos;domainStrategy&apos;:&apos;IPIfNonMatch&apos;,&apos;rules&apos;:[{&apos;type&apos;:&apos;field&apos;,&apos;port&apos;:null,&apos;outboundTag&apos;:&apos;direct&apos;,&apos;ip&apos;:[&apos;0.0.0.0/8&apos;,&apos;10.0.0.0/8&apos;,&apos;100.64.0.0/10&apos;,&apos;127.0.0.0/8&apos;,&apos;169.254.0.0/16&apos;,&apos;172.16.0.0/12&apos;,&apos;192.0.0.0/24&apos;,&apos;192.0.2.0/24&apos;,&apos;192.168.0.0/16&apos;,&apos;198.18.0.0/15&apos;,&apos;198.51.100.0/24&apos;,&apos;203.0.113.0/24&apos;,&apos;::1/128&apos;,&apos;fc00::/7&apos;,&apos;fe80::/10&apos;],&apos;domain&apos;:null},{&apos;type&apos;:&apos;field&apos;,&apos;port&apos;:null,&apos;outboundTag&apos;:&apos;direct&apos;,&apos;ip&apos;:null,&apos;domain&apos;:[&apos;geosite:cn&apos;]},{&apos;type&apos;:&apos;field&apos;,&apos;port&apos;:null,&apos;outboundTag&apos;:&apos;direct&apos;,&apos;ip&apos;:[&apos;geo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TplRouting {
            get {
                return ResourceManager.GetString("TplRouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&apos;network&apos;:&apos;tcp&apos;,&apos;security&apos;:&apos;&apos;,&apos;tcpSettings&apos;:null,&apos;kcpSettings&apos;:null,&apos;wsSettings&apos;:null} 的本地化字符串。
        /// </summary>
        internal static string TplTCP {
            get {
                return ResourceManager.GetString("TplTCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&apos;network&apos;:&apos;ws&apos;,&apos;security&apos;:&apos;tls&apos;,&apos;tcpSettings&apos;:null,&apos;kcpSettings&apos;:null,&apos;wsSettings&apos;:{&apos;connectionReuse&apos;:true,&apos;path&apos;:&apos;/ray&apos;,&apos;headers&apos;:null}} 的本地化字符串。
        /// </summary>
        internal static string TplWS {
            get {
                return ResourceManager.GetString("TplWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray:// 的本地化字符串。
        /// </summary>
        internal static string V2RayLinkPerfix {
            get {
                return ResourceManager.GetString("V2RayLinkPerfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v3.15 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmess:// 的本地化字符串。
        /// </summary>
        internal static string VmessLinkPerfix {
            get {
                return ResourceManager.GetString("VmessLinkPerfix", resourceCulture);
            }
        }
    }
}
