//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayGCon.Resource.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StrConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StrConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayGCon.Resource.Resx.StrConst", typeof(StrConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 030buy.com
        ///0rz.tw
        ///1-apple.com.tw
        ///1000giri.net
        ///100ke.org
        ///10conditionsoflove.com
        ///10musume.com
        ///123rf.com
        ///12bet.com
        ///12vpn.com
        ///12vpn.net
        ///14.102.250.18
        ///14.102.250.19
        ///141hongkong.com
        ///141tube.com
        ///1688.com.au
        ///173ng.com
        ///174.142.105.153
        ///177pic.info
        ///17t17p.com
        ///18board.com
        ///18board.info
        ///18onlygirls.com
        ///18p2p.com
        ///18virginsex.com
        ///1949er.org
        ///1984bbs.com
        ///1984bbs.org
        ///1989report.hkja.org.hk
        ///199.59.148.20
        ///1991way.com
        ///1998cdp.org
        ///1bao.org
        ///1dumb.com
        ///1e100.net
        ///1eew.com
        ///1mobile.com
        ///1mobile.tw
        ///1pondo.tv
        ///2-hand.info
        ///2000fun.com
        ///2008x [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 45.33.128.0/20
        ///64.233.160.0/19
        ///66.102.0.0/20
        ///66.249.80.0/20
        ///72.14.192.0/18
        ///74.125.0.0/16
        ///91.108.4.0/22
        ///91.108.8.0/21
        ///91.108.20.0/22
        ///91.108.36.0/22
        ///91.108.56.0/22
        ///101.127.206.0/23
        ///101.127.208.0/23
        ///107.178.32.0/20
        ///108.177.8.0/21
        ///109.239.140.0/24
        ///149.154.160.0/20
        ///173.194.0.0/16
        ///209.85.128.0/17
        ///216.58.192.0/19
        ///216.239.32.0/19
        /// 的本地化字符串。
        /// </summary>
        internal static string black_cidr {
            get {
                return ResourceManager.GetString("black_cidr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 bug.txt 的本地化字符串。
        /// </summary>
        internal static string BugFileName {
            get {
                return ResourceManager.GetString("BugFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;inTpl&quot;: {
        ///    &quot;port&quot;: 1080,
        ///    &quot;listen&quot;: &quot;127.0.0.1&quot;,
        ///    &quot;protocol&quot;: &quot;协议名称&quot;,
        ///    &quot;settings&quot;: {},
        ///    &quot;streamSettings&quot;: {},
        ///    &quot;tag&quot;: &quot;标识&quot;,
        ///    &quot;sniffing&quot;: {
        ///      &quot;enabled&quot;: false,
        ///      &quot;destOverride&quot;: [
        ///        &quot;http&quot;,
        ///        &quot;tls&quot;
        ///      ]
        ///    }
        ///  },
        ///  &quot;inSS&quot;: {
        ///    &quot;email&quot;: &quot;love@v2ray.com&quot;,
        ///    &quot;method&quot;: &quot;aes-128-cfb&quot;,
        ///    &quot;password&quot;: &quot;密码&quot;,
        ///    &quot;udp&quot;: false,
        ///    &quot;level&quot;: 0,
        ///    &quot;ota&quot;: true,
        ///    &quot;network&quot;: &quot;tcp&quot;
        ///  },
        ///  &quot;inHTTP&quot;: {
        ///    &quot;timeout&quot;: 0,
        ///    &quot;accounts&quot;: [
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_example {
            get {
                return ResourceManager.GetString("config_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;log&quot;: {
        ///    &quot;loglevel&quot;: &quot;warning&quot;
        ///  },
        ///  &quot;inbound&quot;: {
        ///    &quot;port&quot;: 1080,
        ///    &quot;listen&quot;: &quot;127.0.0.1&quot;,
        ///    &quot;protocol&quot;: &quot;socks&quot;,
        ///    &quot;settings&quot;: {
        ///      &quot;auth&quot;: &quot;noauth&quot;,
        ///      &quot;udp&quot;: false,
        ///      &quot;ip&quot;: &quot;127.0.0.1&quot;
        ///    }
        ///  },
        ///  &quot;outbound&quot;: {
        ///    &quot;protocol&quot;: &quot;freedom&quot;,
        ///    &quot;settings&quot;: {},
        ///    &quot;tag&quot;: &quot;direct&quot;
        ///  },
        ///  &quot;policy&quot;: {
        ///    &quot;levels&quot;: {
        ///      &quot;0&quot;: {&quot;uplinkOnly&quot;: 0}
        ///    }
        ///  }
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string config_min {
            get {
                return ResourceManager.GetString("config_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;main&quot;: {
        ///    &quot;v2raygcon&quot;: {
        ///      &quot;alias&quot;: &quot;Package&quot;,
        ///      &quot;description&quot;: &quot;&quot;
        ///    },
        ///    &quot;log&quot;: {
        ///      &quot;loglevel&quot;: &quot;warning&quot;
        ///    },
        ///    &quot;inbound&quot;: {
        ///      &quot;port&quot;: 1080,
        ///      &quot;listen&quot;: &quot;127.0.0.1&quot;,
        ///      &quot;protocol&quot;: &quot;socks&quot;,
        ///      &quot;settings&quot;: {
        ///        &quot;auth&quot;: &quot;noauth&quot;,
        ///        &quot;udp&quot;: false,
        ///        &quot;ip&quot;: &quot;127.0.0.1&quot;
        ///      }
        ///    },
        ///    &quot;outbound&quot;: {
        ///      &quot;mux&quot;: {
        ///        &quot;enabled&quot;: true,
        ///        &quot;concurrency&quot;: 24
        ///      },
        ///      &quot;protocol&quot;: &quot;vmess&quot;,
        ///      &quot;tag&quot;: &quot;agentout&quot;
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_pkg {
            get {
                return ResourceManager.GetString("config_pkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;emptyInOut&quot;: {
        ///    &quot;inbound&quot;: {},
        ///    &quot;outbound&quot;: {}
        ///  },
        ///  &quot;dtrMTProto&quot;: {
        ///    &quot;inboundDetour&quot;: [
        ///      {
        ///        &quot;protocol&quot;: &quot;mtproto&quot;,
        ///        &quot;port&quot;: &quot;443&quot;,
        ///        &quot;tag&quot;: &quot;tg-in&quot;,
        ///        &quot;settings&quot;: {
        ///          &quot;users&quot;: [
        ///            {}
        ///          ]
        ///        }
        ///      }
        ///    ],
        ///    &quot;outboundDetour&quot;: [
        ///      {
        ///        &quot;protocol&quot;: &quot;mtproto&quot;,
        ///        &quot;tag&quot;: &quot;tg-out&quot;,
        ///        &quot;settings&quot;: {}
        ///      }
        ///    ],
        ///    &quot;routing&quot;: {
        ///      &quot;strategy&quot;: &quot;rules&quot;,
        ///      &quot;settings&quot;: {
        ///        &quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string config_tpl {
            get {
                return ResourceManager.GetString("config_tpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10 的本地化字符串。
        /// </summary>
        internal static string DecodeCacheSize {
            get {
                return ResourceManager.GetString("DecodeCacheSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v3.26 的本地化字符串。
        /// </summary>
        internal static string DefCoreVersion {
            get {
                return ResourceManager.GetString("DefCoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/v2ray/v2ray-core/releases/download/{0}/{1} 的本地化字符串。
        /// </summary>
        internal static string DownloadLinkTpl {
            get {
                return ResourceManager.GetString("DownloadLinkTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmess://ew0KICAicHMiOiAiZHVtbXkxIiwNCiAgImFkZCI6ICIxLjIuMy40IiwNCiAgInBvcnQiOiAiNDQzIiwNCiAgImlkIjogImI4NzNkNWY0LTMyNjEtNGYxOS04MGE3LWYwZTY3YzkwYzA4MiIsDQogICJhaWQiOiAiMTAwIiwNCiAgIm5ldCI6ICJ3cyIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIvcmF5IiwNCiAgInRscyI6ICJ0bHMiDQp9 的本地化字符串。
        /// </summary>
        internal static string DummyServ1 {
            get {
                return ResourceManager.GetString("DummyServ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vmess://ew0KICAicHMiOiAiZHVtbXkyIiwNCiAgImFkZCI6ICIyLjMuNC41IiwNCiAgInBvcnQiOiAiMTIzNCIsDQogICJpZCI6ICI1NjIxODM4ZS1hYmM1LTRiNmQtOWQzMS00MmUwOGE3ZWMzMmYiLA0KICAiYWlkIjogIjY0IiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInRscyI6ICIiDQp9 的本地化字符串。
        /// </summary>
        internal static string DummyServ2 {
            get {
                return ResourceManager.GetString("DummyServ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray.exe 的本地化字符串。
        /// </summary>
        internal static string Executable {
            get {
                return ResourceManager.GetString("Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Json File|*.json|All File|*.* 的本地化字符串。
        /// </summary>
        internal static string ExtJson {
            get {
                return ResourceManager.GetString("ExtJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG Files|*.png|All File|*.* 的本地化字符串。
        /// </summary>
        internal static string ExtPng {
            get {
                return ResourceManager.GetString("ExtPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text File|*.txt|All File|*.* 的本地化字符串。
        /// </summary>
        internal static string ExtText {
            get {
                return ResourceManager.GetString("ExtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/v2ray/v2ray-core/releases/latest 的本地化字符串。
        /// </summary>
        internal static string LatestCoreLink {
            get {
                return ResourceManager.GetString("LatestCoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 180 的本地化字符串。
        /// </summary>
        internal static string LazyGCDelay {
            get {
                return ResourceManager.GetString("LazyGCDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 的本地化字符串。
        /// </summary>
        internal static string LazySaveServerListDelay {
            get {
                return ResourceManager.GetString("LazySaveServerListDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;title&gt;Page Title&lt;/title&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///    &lt;script src=&quot;__PacServerUrl__&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;div&gt;&lt;span id=&quot;output&quot;&gt;&lt;/span&gt;&lt;/div&gt;
        ///    &lt;div&gt;&lt;input type=&quot;text&quot; id=&quot;input&quot; onchange=&quot;InputChanged();&quot;&gt;&lt;/div&gt;
        ///    &lt;script&gt;
        ///        var isPlainHostName = function(c) {
        ///            return c.indexOf(&quot;.&quot;) &lt; 0;
        ///    [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PacDebuggerTpl {
            get {
                return ResourceManager.GetString("PacDebuggerTpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10800 的本地化字符串。
        /// </summary>
        internal static string PacmanInitPort {
            get {
                return ResourceManager.GetString("PacmanInitPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 tag 的本地化字符串。
        /// </summary>
        internal static string PacmanTagPrefix {
            get {
                return ResourceManager.GetString("PacmanTagPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     ];
        ///
        ///function ip2decimal(o) { var c = o.split(&quot;.&quot;); return 256 * (256 * (256 * +c[0] + +c[1]) + +c[2]) + +c[3] }
        ///
        ///function FindProxyForURL(o, c) {
        ///    if (/\d+\.\d+\.\d+\.\d+/.test(c)) {
        ///        if (isInNet(dnsResolve(c), &quot;10.0.0.0&quot;, &quot;255.0.0.0&quot;) ||
        ///            isInNet(dnsResolve(c), &quot;172.16.0.0&quot;, &quot;255.240.0.0&quot;) ||
        ///            isInNet(dnsResolve(c), &quot;192.168.0.0&quot;, &quot;255.255.0.0&quot;) ||
        ///            isInNet(dnsResolve(c), &quot;127.0.0.0&quot;, &quot;255.255.255.0&quot;))
        ///            return &quot;DIRECT&quot;;
        ///
        ///        for (var [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string PacTemplateTail {
            get {
                return ResourceManager.GetString("PacTemplateTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5 的本地化字符串。
        /// </summary>
        internal static string ParseImportDepth {
            get {
                return ResourceManager.GetString("ParseImportDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3 的本地化字符串。
        /// </summary>
        internal static string ParseImportRetry {
            get {
                return ResourceManager.GetString("ParseImportRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 的本地化字符串。
        /// </summary>
        internal static string ParseImportTimeOut {
            get {
                return ResourceManager.GetString("ParseImportTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{4}) 的本地化字符串。
        /// </summary>
        internal static string PatternBase64 {
            get {
                return ResourceManager.GetString("PatternBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [A-Za-z0-9+/]+ 的本地化字符串。
        /// </summary>
        internal static string PatternBase64NonStandard {
            get {
                return ResourceManager.GetString("PatternBase64NonStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /v2ray/v2ray-core/releases/download/(v[\.0-9]+)/v2ray-windows-64.zip 的本地化字符串。
        /// </summary>
        internal static string PatternDownloadLink {
            get {
                return ResourceManager.GetString("PatternDownloadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /nobody3u/V2RayGCon/releases/tag/([\.0-9]+) 的本地化字符串。
        /// </summary>
        internal static string PatternLatestVGC {
            get {
                return ResourceManager.GetString("PatternLatestVGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [^0-9a-zA-Z] 的本地化字符串。
        /// </summary>
        internal static string PatternNonAlphabet {
            get {
                return ResourceManager.GetString("PatternNonAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray-windows-32.zip 的本地化字符串。
        /// </summary>
        internal static string PkgWin32 {
            get {
                return ResourceManager.GetString("PkgWin32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v2ray-windows-64.zip 的本地化字符串。
        /// </summary>
        internal static string PkgWin64 {
            get {
                return ResourceManager.GetString("PkgWin64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/v2ray/v2ray-core/releases 的本地化字符串。
        /// </summary>
        internal static string ReleasePageUrl {
            get {
                return ResourceManager.GetString("ReleasePageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 的本地化字符串。
        /// </summary>
        internal static string SpeedTestTimeout {
            get {
                return ResourceManager.GetString("SpeedTestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://www.google.com 的本地化字符串。
        /// </summary>
        internal static string SpeedTestUrl {
            get {
                return ResourceManager.GetString("SpeedTestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/nobody3u/V2RayGCon/releases/tag/{0} 的本地化字符串。
        /// </summary>
        internal static string TplUrlVGCRelease {
            get {
                return ResourceManager.GetString("TplUrlVGCRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/nobody3u/V2RayGCon/releases/latest 的本地化字符串。
        /// </summary>
        internal static string UrlLatestVGC {
            get {
                return ResourceManager.GetString("UrlLatestVGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 v3.45,v3.43,v3.41 的本地化字符串。
        /// </summary>
        internal static string VerList {
            get {
                return ResourceManager.GetString("VerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 https://github.com/nobody3u/V2RayGCon/wiki/vlink 的本地化字符串。
        /// </summary>
        internal static string VlinkWiki {
            get {
                return ResourceManager.GetString("VlinkWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0-6.com
        ///0001688.com
        ///001cndc.com
        ///001en.com
        ///001jm.com
        ///001job.com
        ///001pp.com
        ///001sj.net
        ///001sxy.com
        ///001uk.com
        ///001xin.com
        ///005.tv
        ///00615.net
        ///007swz.com
        ///00817.com
        ///0086gd.com
        ///01-123.com
        ///010lf.com
        ///01dai.com
        ///01dianzi.com
        ///01hr.com
        ///01w.com
        ///01wed.com
        ///020.com
        ///020h.com
        ///020job.com
        ///020p.net
        ///0214.com
        ///022china.com
        ///022job.net
        ///022net.com
        ///022s.com
        ///022v.com
        ///0231230.com
        ///023zp.com
        ///024anfang.net
        ///024zxw.com
        ///025ct.com
        ///025syedu.com
        ///025xl.com
        ///025zp.com
        ///027.net
        ///027art.com
        ///029k.com
        ///0312mc.com
        ///0316.cc
        ///0352fang.com
        ///0356f.com
        ///0357hz.com
        ///0371gao [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.0.1.0/24
        ///1.0.2.0/23
        ///1.0.8.0/21
        ///1.0.32.0/19
        ///1.1.0.0/24
        ///1.1.2.0/23
        ///1.1.4.0/22
        ///1.1.8.0/21
        ///1.1.16.0/20
        ///1.1.32.0/19
        ///1.2.0.0/23
        ///1.2.2.0/24
        ///1.2.4.0/22
        ///1.2.8.0/21
        ///1.2.16.0/20
        ///1.2.32.0/19
        ///1.2.64.0/18
        ///1.3.0.0/16
        ///1.4.1.0/24
        ///1.4.2.0/23
        ///1.4.4.0/22
        ///1.4.8.0/21
        ///1.4.16.0/20
        ///1.4.32.0/19
        ///1.4.64.0/18
        ///1.8.0.0/16
        ///1.10.0.0/21
        ///1.10.8.0/23
        ///1.10.11.0/24
        ///1.10.12.0/22
        ///1.10.16.0/20
        ///1.10.32.0/19
        ///1.10.64.0/18
        ///1.12.0.0/14
        ///1.24.0.0/13
        ///1.45.0.0/16
        ///1.48.0.0/14
        ///1.56.0.0/13
        ///1.68.0.0/14
        ///1.80.0.0/12
        ///1.116.0.0/14
        ///1.180.0.0/14
        ///1.184.0.0/15
        ///1.188 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string white_cidr {
            get {
                return ResourceManager.GetString("white_cidr", resourceCulture);
            }
        }
    }
}
