//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayGCon.Resource.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayGCon.Resource.Resx.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save current config as new server? 的本地化字符串。
        /// </summary>
        internal static string AddNewServer {
            get {
                return ResourceManager.GetString("AddNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add server 的本地化字符串。
        /// </summary>
        internal static string AddServer {
            get {
                return ResourceManager.GetString("AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add server fail, please check your settings. 的本地化字符串。
        /// </summary>
        internal static string AddServFail {
            get {
                return ResourceManager.GetString("AddServFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add server success! 的本地化字符串。
        /// </summary>
        internal static string AddServSuccess {
            get {
                return ResourceManager.GetString("AddServSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analysing import, please wait ... 的本地化字符串。
        /// </summary>
        internal static string AnalysingImport {
            get {
                return ResourceManager.GetString("AnalysingImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available examples ... 的本地化字符串。
        /// </summary>
        internal static string AvailableExamples {
            get {
                return ResourceManager.GetString("AvailableExamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel current download? 的本地化字符串。
        /// </summary>
        internal static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not parse json! Discard changes? 的本地化字符串。
        /// </summary>
        internal static string CannotParseJson {
            get {
                return ResourceManager.GetString("CannotParseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: can not lauch v2ray-core. 的本地化字符串。
        /// </summary>
        internal static string CantLauchCore {
            get {
                return ResourceManager.GetString("CantLauchCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CF and Google 的本地化字符串。
        /// </summary>
        internal static string CFnGoogle {
            get {
                return ResourceManager.GetString("CFnGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close window? 的本地化字符串。
        /// </summary>
        internal static string ConfirmCloseWindow {
            get {
                return ResourceManager.GetString("ConfirmCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DELETE ALL SERVERS? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteAllServers {
            get {
                return ResourceManager.GetString("ConfirmDeleteAllServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete selected server? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteServer {
            get {
                return ResourceManager.GetString("ConfirmDeleteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New V2RayGCon v{0} is available.
        ///Checkout download page? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDownloadNewVGC {
            get {
                return ResourceManager.GetString("ConfirmDownloadNewVGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit program? 的本地化字符串。
        /// </summary>
        internal static string ConfirmExitApp {
            get {
                return ResourceManager.GetString("ConfirmExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current config will be cleared!
        ///Load new config? 的本地化字符串。
        /// </summary>
        internal static string ConfirmLoadNewServer {
            get {
                return ResourceManager.GetString("ConfirmLoadNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save current config? 的本地化字符串。
        /// </summary>
        internal static string ConfirmSaveCurConfig {
            get {
                return ResourceManager.GetString("ConfirmSaveCurConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy fail! 的本地化字符串。
        /// </summary>
        internal static string CopyFail {
            get {
                return ResourceManager.GetString("CopyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied to clipboard. 的本地化字符串。
        /// </summary>
        internal static string CopySuccess {
            get {
                return ResourceManager.GetString("CopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not set local proxy address! 的本地化字符串。
        /// </summary>
        internal static string CoreCantSetLocalAddr {
            get {
                return ResourceManager.GetString("CoreCantSetLocalAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2ray-core has stopped! 的本地化字符串。
        /// </summary>
        internal static string CoreExit {
            get {
                return ResourceManager.GetString("CoreExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current v2ray-core version is v{0} 的本地化字符串。
        /// </summary>
        internal static string CurrentCoreVerIs {
            get {
                return ResourceManager.GetString("CurrentCoreVerIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data too big. Please trim down the config file. 的本地化字符串。
        /// </summary>
        internal static string DataTooBig {
            get {
                return ResourceManager.GetString("DataTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decode fail. 的本地化字符串。
        /// </summary>
        internal static string DecodeFail {
            get {
                return ResourceManager.GetString("DecodeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decode import fail! 的本地化字符串。
        /// </summary>
        internal static string DecodeImportFail {
            get {
                return ResourceManager.GetString("DecodeImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to decode v-link! 的本地化字符串。
        /// </summary>
        internal static string DecodeVLinkFail {
            get {
                return ResourceManager.GetString("DecodeVLinkFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2Ray GUI Configer 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download cancelled! 的本地化字符串。
        /// </summary>
        internal static string DownloadCancelled {
            get {
                return ResourceManager.GetString("DownloadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download v2ray-core completed! 的本地化字符串。
        /// </summary>
        internal static string DownloadCompleted {
            get {
                return ResourceManager.GetString("DownloadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download fail!
        ///You can download manually from the link below.
        ///https://github.com/v2ray/v2ray-core 的本地化字符串。
        /// </summary>
        internal static string DownloadFail {
            get {
                return ResourceManager.GetString("DownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading, please wait ... 的本地化字符串。
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download progress 的本地化字符串。
        /// </summary>
        internal static string DownloadProgress {
            get {
                return ResourceManager.GetString("DownloadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download v2ray-core 的本地化字符串。
        /// </summary>
        internal static string DownloadV2rayCore {
            get {
                return ResourceManager.GetString("DownloadV2rayCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate server 的本地化字符串。
        /// </summary>
        internal static string DuplicateServer {
            get {
                return ResourceManager.GetString("DuplicateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot load server config. Using default config! 的本地化字符串。
        /// </summary>
        internal static string EditorCannotLoadServerConfig {
            get {
                return ResourceManager.GetString("EditorCannotLoadServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not parse json! Please check you config. 的本地化字符串。
        /// </summary>
        internal static string EditorCheckConfig {
            get {
                return ResourceManager.GetString("EditorCheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config is invalid.
        ///Discard latest changes and continue? 的本地化字符串。
        /// </summary>
        internal static string EditorDiscardChange {
            get {
                return ResourceManager.GetString("EditorDiscardChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No example for this part. 的本地化字符串。
        /// </summary>
        internal static string EditorNoExample {
            get {
                return ResourceManager.GetString("EditorNoExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config has change, save it now? 的本地化字符串。
        /// </summary>
        internal static string EditorSaveChange {
            get {
                return ResourceManager.GetString("EditorSaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Empty) 的本地化字符串。
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link is empty! 的本地化字符串。
        /// </summary>
        internal static string EmptyLink {
            get {
                return ResourceManager.GetString("EmptyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please download v2ray-core first!（checkout systray icon&apos;s popup menu.） 的本地化字符串。
        /// </summary>
        internal static string ExeNotFound {
            get {
                return ResourceManager.GetString("ExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found! 的本地化字符串。
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail to generate v-link! 的本地化字符串。
        /// </summary>
        internal static string GenVLinkFail {
            get {
                return ResourceManager.GetString("GenVLinkFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get v2ray-core version fail! 的本地化字符串。
        /// </summary>
        internal static string GetCoreVerFail {
            get {
                return ResourceManager.GetString("GetCoreVerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get latest version fail! 的本地化字符串。
        /// </summary>
        internal static string GetLatestVerFail {
            get {
                return ResourceManager.GetString("GetLatestVerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get v2ray-core versions list fail! 的本地化字符串。
        /// </summary>
        internal static string GetVersionListFail {
            get {
                return ResourceManager.GetString("GetVersionListFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get V2RayGCon latest version number fail! 的本地化字符串。
        /// </summary>
        internal static string GetVGCVerFail {
            get {
                return ResourceManager.GetString("GetVGCVerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import links from clipboard 的本地化字符串。
        /// </summary>
        internal static string ImportLink {
            get {
                return ResourceManager.GetString("ImportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found no link! 的本地化字符串。
        /// </summary>
        internal static string ImportLinkFail {
            get {
                return ResourceManager.GetString("ImportLinkFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Success! 的本地化字符串。
        /// </summary>
        internal static string ImportLinkSuccess {
            get {
                return ResourceManager.GetString("ImportLinkSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 latest 的本地化字符串。
        /// </summary>
        internal static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Links has been copied to clipboard. 的本地化字符串。
        /// </summary>
        internal static string LinksCopied {
            get {
                return ResourceManager.GetString("LinksCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load json file fail! 的本地化字符串。
        /// </summary>
        internal static string LoadJsonFail {
            get {
                return ResourceManager.GetString("LoadJsonFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network timeout 的本地化字符串。
        /// </summary>
        internal static string NetworkTimeout {
            get {
                return ResourceManager.GetString("NetworkTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No links found. 的本地化字符串。
        /// </summary>
        internal static string NoLinkFound {
            get {
                return ResourceManager.GetString("NoLinkFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current V2RayGCon is the latest version. 的本地化字符串。
        /// </summary>
        internal static string NoNewVGC {
            get {
                return ResourceManager.GetString("NoNewVGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find any QR code. 的本地化字符串。
        /// </summary>
        internal static string NoQRCode {
            get {
                return ResourceManager.GetString("NoQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate link or unable to decode 的本地化字符串。
        /// </summary>
        internal static string NotSupportLinkType {
            get {
                return ResourceManager.GetString("NotSupportLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find original config!
        ///Please use [Add new server] or [Replace server]. 的本地化字符串。
        /// </summary>
        internal static string OrgServNotFound {
            get {
                return ResourceManager.GetString("OrgServNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not parse json! Please check current config. 的本地化字符串。
        /// </summary>
        internal static string PleaseCheckConfig {
            get {
                return ResourceManager.GetString("PleaseCheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy all website 的本地化字符串。
        /// </summary>
        internal static string ProxyModeAll {
            get {
                return ResourceManager.GetString("ProxyModeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No proxy 的本地化字符串。
        /// </summary>
        internal static string ProxyModeNone {
            get {
                return ResourceManager.GetString("ProxyModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy accroding to PAC setting 的本地化字符串。
        /// </summary>
        internal static string ProxyModePAC {
            get {
                return ResourceManager.GetString("ProxyModePAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reason 的本地化字符串。
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use current config to replace selected server? 的本地化字符串。
        /// </summary>
        internal static string ReplaceServer {
            get {
                return ResourceManager.GetString("ReplaceServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as 的本地化字符串。
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan QR code 的本地化字符串。
        /// </summary>
        internal static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server list is empty! 的本地化字符串。
        /// </summary>
        internal static string ServerListIsEmpty {
            get {
                return ResourceManager.GetString("ServerListIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set proxy mode 的本地化字符串。
        /// </summary>
        internal static string SetProxyMode {
            get {
                return ResourceManager.GetString("SetProxyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config Editor 的本地化字符串。
        /// </summary>
        internal static string ShowConfigWin {
            get {
                return ResourceManager.GetString("ShowConfigWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Log 的本地化字符串。
        /// </summary>
        internal static string ShowLogWin {
            get {
                return ResourceManager.GetString("ShowLogWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Window 的本地化字符串。
        /// </summary>
        internal static string ShowMainWin {
            get {
                return ResourceManager.GetString("ShowMainWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success. 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use decode cache. 的本地化字符串。
        /// </summary>
        internal static string UsingDecodeCache {
            get {
                return ResourceManager.GetString("UsingDecodeCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vist v-link wiki page? 的本地化字符串。
        /// </summary>
        internal static string VisitVlinkPage {
            get {
                return ResourceManager.GetString("VisitVlinkPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vist project page? 的本地化字符串。
        /// </summary>
        internal static string VistPorjectPage {
            get {
                return ResourceManager.GetString("VistPorjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit wiki page of this project? 的本地化字符串。
        /// </summary>
        internal static string VistWikiPage {
            get {
                return ResourceManager.GetString("VistWikiPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice! IE not support PAC. 的本地化字符串。
        /// </summary>
        internal static string WarnIENotSupportPac {
            get {
                return ResourceManager.GetString("WarnIENotSupportPac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Another instance is already running.
        ///Are you sure to launch another one? 的本地化字符串。
        /// </summary>
        internal static string WarnMultipleInstance {
            get {
                return ResourceManager.GetString("WarnMultipleInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 32bit 的本地化字符串。
        /// </summary>
        internal static string Win32 {
            get {
                return ResourceManager.GetString("Win32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 64bit 的本地化字符串。
        /// </summary>
        internal static string Win64 {
            get {
                return ResourceManager.GetString("Win64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write to file fail! 的本地化字符串。
        /// </summary>
        internal static string WriteFileFail {
            get {
                return ResourceManager.GetString("WriteFileFail", resourceCulture);
            }
        }
    }
}
