//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace V2RayGCon.Resource.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("V2RayGCon.Resource.Resx.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2RayGCon 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not parse json! Discard changes? 的本地化字符串。
        /// </summary>
        internal static string CannotParseJson {
            get {
                return ResourceManager.GetString("CannotParseJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: can not lauch v2ray-core. 的本地化字符串。
        /// </summary>
        internal static string CantLauchCore {
            get {
                return ResourceManager.GetString("CantLauchCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete selected server? 的本地化字符串。
        /// </summary>
        internal static string ConfirmDeleteServer {
            get {
                return ResourceManager.GetString("ConfirmDeleteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit program? 的本地化字符串。
        /// </summary>
        internal static string ConfirmExitApp {
            get {
                return ResourceManager.GetString("ConfirmExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy fail! 的本地化字符串。
        /// </summary>
        internal static string CopyFail {
            get {
                return ResourceManager.GetString("CopyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not set local proxy address! 的本地化字符串。
        /// </summary>
        internal static string CoreCantSetLocalAddr {
            get {
                return ResourceManager.GetString("CoreCantSetLocalAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2ray-core has stopped! 的本地化字符串。
        /// </summary>
        internal static string CoreExit {
            get {
                return ResourceManager.GetString("CoreExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V2Ray GUI Configer 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download v2ray-core completed! 的本地化字符串。
        /// </summary>
        internal static string DLComplete {
            get {
                return ResourceManager.GetString("DLComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download fail! 的本地化字符串。
        /// </summary>
        internal static string DLFail {
            get {
                return ResourceManager.GetString("DLFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download v2ray-core 的本地化字符串。
        /// </summary>
        internal static string DLv2rayCore {
            get {
                return ResourceManager.GetString("DLv2rayCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading, please wait ... 的本地化字符串。
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot load server config. Using default config! 的本地化字符串。
        /// </summary>
        internal static string EditorCannotLoadServerConfig {
            get {
                return ResourceManager.GetString("EditorCannotLoadServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not parse json! Please check you config. 的本地化字符串。
        /// </summary>
        internal static string EditorCheckConfig {
            get {
                return ResourceManager.GetString("EditorCheckConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config has change but not save yet. Discard change? 的本地化字符串。
        /// </summary>
        internal static string EditorDiscardChange {
            get {
                return ResourceManager.GetString("EditorDiscardChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No example for this part. 的本地化字符串。
        /// </summary>
        internal static string EditorNoExample {
            get {
                return ResourceManager.GetString("EditorNoExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config has change, save it now? 的本地化字符串。
        /// </summary>
        internal static string EditorSaveChange {
            get {
                return ResourceManager.GetString("EditorSaveChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please download v2ray-core first!（checkout systray icon&apos;s popup menu.） 的本地化字符串。
        /// </summary>
        internal static string ExeNotFound {
            get {
                return ResourceManager.GetString("ExeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import links from clipboard 的本地化字符串。
        /// </summary>
        internal static string ImportLink {
            get {
                return ResourceManager.GetString("ImportLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found no link! 的本地化字符串。
        /// </summary>
        internal static string ImportLinkFail {
            get {
                return ResourceManager.GetString("ImportLinkFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Success! 的本地化字符串。
        /// </summary>
        internal static string ImportLinkSuccess {
            get {
                return ResourceManager.GetString("ImportLinkSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Links has been copied to clipboard. 的本地化字符串。
        /// </summary>
        internal static string LinksCopied {
            get {
                return ResourceManager.GetString("LinksCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find any QR code. 的本地化字符串。
        /// </summary>
        internal static string NoQRCode {
            get {
                return ResourceManager.GetString("NoQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate link or unable to decode 的本地化字符串。
        /// </summary>
        internal static string NotSupportLinkType {
            get {
                return ResourceManager.GetString("NotSupportLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan QR code 的本地化字符串。
        /// </summary>
        internal static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config Editor 的本地化字符串。
        /// </summary>
        internal static string ShowConfigWin {
            get {
                return ResourceManager.GetString("ShowConfigWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Log 的本地化字符串。
        /// </summary>
        internal static string ShowLogWin {
            get {
                return ResourceManager.GetString("ShowLogWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Window 的本地化字符串。
        /// </summary>
        internal static string ShowMainWin {
            get {
                return ResourceManager.GetString("ShowMainWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 32bit 的本地化字符串。
        /// </summary>
        internal static string Win32 {
            get {
                return ResourceManager.GetString("Win32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 64bit 的本地化字符串。
        /// </summary>
        internal static string Win64 {
            get {
                return ResourceManager.GetString("Win64", resourceCulture);
            }
        }
    }
}
